/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppReportsUnsoldRouteImport } from './routes/_app.reports.unsold'
import { Route as AppInvoicesIdRouteImport } from './routes/_app.invoices.$id'
import { Route as AppCompaniesIdRouteImport } from './routes/_app.companies.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsUnsoldRoute = AppReportsUnsoldRouteImport.update({
  id: '/reports/unsold',
  path: '/reports/unsold',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppCompaniesIdRoute = AppCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/sales': typeof AppSalesRoute
  '/companies/$id': typeof AppCompaniesIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/reports/unsold': typeof AppReportsUnsoldRoute
}
export interface FileRoutesByTo {
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/sales': typeof AppSalesRoute
  '/': typeof AppIndexRoute
  '/companies/$id': typeof AppCompaniesIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/reports/unsold': typeof AppReportsUnsoldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/invoices': typeof AppInvoicesRouteWithChildren
  '/_app/sales': typeof AppSalesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/companies/$id': typeof AppCompaniesIdRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/reports/unsold': typeof AppReportsUnsoldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inventory'
    | '/invoices'
    | '/sales'
    | '/companies/$id'
    | '/invoices/$id'
    | '/reports/unsold'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/inventory'
    | '/invoices'
    | '/sales'
    | '/'
    | '/companies/$id'
    | '/invoices/$id'
    | '/reports/unsold'
  id:
    | '__root__'
    | '/_app'
    | '/_app/inventory'
    | '/_app/invoices'
    | '/_app/sales'
    | '/_app/'
    | '/_app/companies/$id'
    | '/_app/invoices/$id'
    | '/_app/reports/unsold'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/unsold': {
      id: '/_app/reports/unsold'
      path: '/reports/unsold'
      fullPath: '/reports/unsold'
      preLoaderRoute: typeof AppReportsUnsoldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/companies/$id': {
      id: '/_app/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AppCompaniesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppInvoicesRouteChildren {
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesIdRoute: AppInvoicesIdRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppRouteChildren {
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppSalesRoute: typeof AppSalesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCompaniesIdRoute: typeof AppCompaniesIdRoute
  AppReportsUnsoldRoute: typeof AppReportsUnsoldRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppSalesRoute: AppSalesRoute,
  AppIndexRoute: AppIndexRoute,
  AppCompaniesIdRoute: AppCompaniesIdRoute,
  AppReportsUnsoldRoute: AppReportsUnsoldRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
